### ISSUE TITLE
How to get the chip Object on delete / click

### ISSUE THREAD

**Issue by ado2000** [FlowingCode/ChipFieldAddon#26]
Hi, at the moment when a Chip is clicked or deleted, I can get the chip label by the event.getLabe().

In my case I pass an objet to the chipField " ChipField<MyObject>....."
How can I get the MyObject on click / delete ?

Thanks

**Comment by javier-godoy** [comment]
Hello. The component uses the label for identifying chips in the client side, 

https://github.com/FlowingCode/ChipFieldAddon/blob/5e63c61626d46c2eb7a3530dbd1decbee48cde86/src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java#L73

but the mapping is not exposed through public API, so, we'll need to implement a mechanism that allows retrieving an item given its value. Indeed, that's the approach in Grid's listeners: 
https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ItemClickEvent.java#L83-L99
