### ISSUE TITLE
Chip can not be used as a standalone component, due to visibility

### ISSUE THREAD

**Issue by lucascapicotto** [FlowingCode/ChipFieldAddon#8]
We want to use the Chip component outside of the ChipField component, all it would it take is changing the visibility of Chip to public.

**Comment by javier-godoy** [comment]
I see it was intentionally made package-private at some point (https://github.com/FlowingCode/ChipFieldAddon/commit/7c9c909506121d5f0364b4bea15d83ba258def25#diff-c053ac6056a1c6514826b0e882562a8f) but it's a good idea.

**Comment by javier-godoy** [comment]
Thanks for the pull request. Changes were released in [version 2.1.0](https://vaadin.com/directory/component/chipfield-addon/2.1.0)
